# Nov 4th workshop Feedback survey
# coding book 

library(readxl)
wrkshp_feedback <- read_excel("wrkshp_feedback.xlsx")



wrkshp_feedback <- wrkshp_feedback %>% rename(
time = "時間戳記",                                                                                                                                                                                                                                                          
lecture_interesting = "1.\tLecture questions.    Please indicate how much do you agree or disagree with each of the following statements according to this scale. [The lectures were interesting]"                                                                                ,        
topic_helps_career = "1.\tLecture questions.    Please indicate how much do you agree or disagree with each of the following statements according to this scale. [The content presented was useful to my academic or professional career]"                                         ,      
topic_important  =  "1.\tLecture questions.    Please indicate how much do you agree or disagree with each of the following statements according to this scale. [The speakers convinced me that their chosen topic was relevant and important]"                                     ,    
spkr_know_topic  ="1.\tLecture questions.    Please indicate how much do you agree or disagree with each of the following statements according to this scale. [The speakers were familiar with their topic]"                                                                         , 
topic_deserves_attention  = "1.\tLecture questions.    Please indicate how much do you agree or disagree with each of the following statements according to this scale. [The topics presented were topics that I think are major public health issues and deserve attention]"         ,          
registration_easy  ="1.\tLecture questions.    Please indicate how much do you agree or disagree with each of the following statements according to this scale. [The registration system was easy to use]"                                                                             , 
mixed_format_ok =  "1.\tLecture questions.    Please indicate how much do you agree or disagree with each of the following statements according to this scale. [The mixed online/ in-person format worked well]"                                                                       ,
in_person_sound_ok = "1.\tLecture questions.    Please indicate how much do you agree or disagree with each of the following statements according to this scale. [I could hear the in-person speakers clearly]"                                                                         , 
online_sound_ok = "1.\tLecture questions.    Please indicate how much do you agree or disagree with each of the following statements according to this scale. [I could hear the online-speakers clearly]"                                                                             ,
in_person_visual_ok ="1.\tLecture questions.    Please indicate how much do you agree or disagree with each of the following statements according to this scale. [I could see the in-person speakers and their presentation slides clearly]"                                           ,  
online_visual_ok ="1.\tLecture questions.    Please indicate how much do you agree or disagree with each of the following statements according to this scale. [I could see the online speakers and their presentation slides clearly]"                                                ,
more_online_speakers = "1.\tLecture questions.    Please indicate how much do you agree or disagree with each of the following statements according to this scale. [I want to see more online speakers]"                                                                               ,    
more_in_person_speakers = "1.\tLecture questions.    Please indicate how much do you agree or disagree with each of the following statements according to this scale. [I would prefer more in-person speakers]"                                                                         ,      
group_discussions_interesting = "1.\tWorkshop questions.    Please indicate how much do you agree or disagree with each of the following statements according to this scale. [The discussion sessions with my small group were interesting]"                                             ,           
group_discussions_help_career = "1.\tWorkshop questions.    Please indicate how much do you agree or disagree with each of the following statements according to this scale. [The discussions with my group were useful to my academic or professional career]"                           ,          
group_discussion_topic_important =  "1.\tWorkshop questions.    Please indicate how much do you agree or disagree with each of the following statements according to this scale. [The topics we discussed in my group were relevant and important]"                                        ,             
mentor_know_topic  =  "1.\tWorkshop questions.    Please indicate how much do you agree or disagree with each of the following statements according to this scale. [The small group mentors were familiar with the assigned health topic]"                                                ,
mentor_know_hp  = "1.\tWorkshop questions.    Please indicate how much do you agree or disagree with each of the following statements according to this scale. [The small group mentors were familiar with the proccess of developing a health promotion project]"                    ,
timing_ok  = "1.\tWorkshop questions.    Please indicate how much do you agree or disagree with each of the following statements according to this scale. [The event was well-timed and transitions made sense]"                                                                 ,
hp_knowledge_increased = "1.\tWorkshop questions.    Please indicate how much do you agree or disagree with each of the following statements according to this scale. [I know more about health promotion as a result of attending this workshop]"                                ,           
core_comp_knowledge_increased = "1.\tWorkshop questions.    Please indicate how much do you agree or disagree with each of the following statements according to this scale. [I know more about the six core competencies for health promotion after attending this workshop]"     ,                 
cchp_awareness_increased = "1.\tWorkshop questions.    Please indicate how much do you agree or disagree with each of the following statements according to this scale. [I know more about the Collaborating Centres for Health Promotion as a result of attending this workshop]"  ,           
connections_made = "1.\tWorkshop questions.    Please indicate how much do you agree or disagree with each of the following statements according to this scale. [I made personal or professional connections with other workshop participants]"                                      ,  
twn_int_lots_of_interactions = "1.\tWorkshop questions.    Please indicate how much do you agree or disagree with each of the following statements according to this scale. [There seemed to be a lot of interaction between the Taiwanese government participants and international participants]",
attend_next_event = "1.\tWorkshop questions.    Please indicate how much do you agree or disagree with each of the following statements according to this scale. [I would attend another event hosted by the Collaborating Centres for Health Promotion]"                               ,
participant_type = "What type of participant were you"                                                                                                                                                                                                                                 ,
focus_area = "4.5 What would you say your focus area is?"                                                                                                                                                                                                                        ,
employer_required = "4.6 Did you attend our event because you were required to attend by your employer?"                                                                                                                                                                          ,      
class_required =  "4.7 Did you attend our event because you were required to attend for class?"                                                                                                                                                                                    ,   
come_ifnot_required = "4.8 If you answered yes to questions 4.6 or 4.7, would you have chosen to attend this event if you weren’t required to attend?"  ,
like_long_resp = "5.1 What did you like about this workshop?"                                                                                            ,                                                                                                                            
dislike_long_resp =  "5.2 What did you dislike about this workshop?"                                                                                      ,                                                                                                                               
unclear_long_resp =  "5.3 Things that were not clear to me…"                                                                                               ,                                                                                                                              
suggestions = "5.4 Any comments or suggestions for CCHP or any of our speakers?"                                                                            ,                                                                                                                      
future_topics = "5.5 What sorts of events or topics would you like to see covered in the future?" 
)
