# trainee namer

library(readxl)
library(dplyr)

trainee_tracking <- read_excel("2020wrkshp_trainee_tracking.xlsx")

trainee_tracking <- trainee_tracking %>% 
  rename(
time=  "時間戳記"                                                                                                                                                                                                                                                                                                                                                                                  ,
name = "1. Your name:"                                                                                                                                                                                                                                                                                                                                                                              ,                                                                                    
date = "2. Today’s date"                                                                                                                                                                                                                                                                                                                                                                             ,                                                                                   
country = "3. Which country are you from?"                                                                                                                                                                                                                                                                                                                                                            ,                                                                                     
degree_completed = "4. Since attending this workshop last year, have you completed the degree that you were studying for at the time of the workshop?"                                                                                                                                                                                                                                                 ,                                                                                             
started_new_degree = "5. Have you started studying for another degree?"                                                                                                                                                                                                                                                                                                                                 ,                                                                                              
currently_working = "6. Are you working now?"                                                                                                                                                                                                                                                                                                                                                            ,                                                                                            
work_location = "7. If you are working, where do you work? What is your job title? If you are not working currently, please enter “NA”    \n_____________[Job title, Employer, Country]"                                                                                                                                                                                                                    ,                                                                                     
competancies_remembered = "8. We discussed 4 core  competencies during the workshop. Do you remember what they were? (Multiple choices)"                                                                                                                                                                                                                                                                   ,                                                                                                
share_with_coworkers = "9. Have you ever shared, either formally or informally, information about the core competencies with your friends or colleagues?",
workshop_helpful = "10. Overall, do you think the workshop was helpful?"                                                                                                                                                                                                                                                                                                                                    ,                                                                                        
competancy_useful_school = "A1. During your time studying in Taiwan, which core competency do you think is/was the  MOST relevant and useful to your schoolwork?"                                                                                                                                                                                                                                            ,                                                                                               
competancy_not_useful_school =  "A2. During your time studying in Taiwan, which core competency do you think is/was the LEAST relevant and useful to your schoolwork?"                                                                                                                                                                                                                                        ,                                                                                                   
schoolwork_changes = "A3. Did the information presented during the workshop change the way you approach your schoolwork?"                                                                                                                                                                                                                                                                                      ,                                                                                       
assignment_using_competancy =  "A4. Could you tell us more about a specific assignment where you used one of  the core competencies? If you have done so for more than one assignment, please   choose one as an example. If you have not applied any of the core concepts, please enter “NA” for all of the following fields.    \nCourse title: _____________________    \nWhat was the assignment? (e.g., final report)_____________________    \nWhich core competency did you apply? _____________________",
competancy_useful_job =  "B1. Which core competency do you think is the MOST relevant and useful to your job?"                                                                                                                                                                                                                                                                                                                                                                                            ,
competancy_not_useful_job =  "B2. Which core competency do you think is the LEAST relevant and useful to your job?"                                                                                                                                                                                                                                                                                                                                                                                        ,   
job_changes = "B3. Has the information you received  during the workshop changed the way you approach any of your job duties?"                                                                                                                                                                                                                                                                                                                                                                 ,
jobtask_using_competancy = "B4. Could you tell us more about a specific work project or job task where you applied the core competencies? If you have done so for more than one project or task, please choose one as an example. If you have not applied any of these concepts, please enter “NA”.    \nPlease briefly describe the project or task?___________________    \nWhich competency did you apply?__________________"                                                                ,            
times_talked_to_trainer = "C1. At the end of the workshop, we encouraged the trainees to keep in contact with their trainer to further develop the projects proposed during the workshop.    \nHow many times  have you discussed your project proposal with your trainer so far?"                                                                                                                                                                                                               ,          
talk_to_trainer_method = "C2. How did you connect with your trainer? Was it by… (multiple choices)"                                                                                                                                                                                                                                                                                                                                                                                               ,        
talk_to_trainer_helpful = "C3. Do you think the discussion with your trainer was helpful?"                                                                                                                                                                                                                                                                                                                                                                                                         ,        
trainer_available = "C4. My trainer is available for advice and support with regard to your requests/questions？"                                                                                                                                                                                                                                                                                                                                                                                   , 
still_in_contact = "C5. Are you still in contact with my trainer?"                                                                                                                                                                                                                                                                                                                                                                                                                                  ,
project_designed = "D1. Have you completed the design phase of your project?"                                                                                                                                                                                                                                                                                                                                                                                                                       ,
projected_implemented = "D2. Have you implemented your project?"                                                                                                                                                                                                                                                                                                                                                                                                                                     ,    
challenges = "D3. You may have experienced several difficulties with the development and implementation of your project. Please select all that apply. (Multiple choice)"                                                                                                                                                                                                                                                                                                                     ,
what_I_wish_I_knew = "D4. Throughout the process, was there anything that you wished that you had known more about? Please write it down."
)

trainee_tracking <- trainee_tracking[3:nrow(trainee_tracking),]


trainee_tracking2  <-  trainee_tracking %>% replace(is.na(.), "No Response") 
trainee_tracking2[trainee_tracking2$country=="Viet Nam",]$country <- "Vietnam"
